################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
device_support/F2837xD_common/source/F2837xD_Adc.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_Adc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_Adc.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_CodeStartBranch.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_CodeStartBranch.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_CodeStartBranch.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_CpuTimers.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_CpuTimers.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_CpuTimers.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_DBGIER.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_DBGIER.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_DBGIER.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_DefaultISR.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_DefaultISR.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_DefaultISR.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_Dma.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_Dma.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_Dma.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_ECap.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_ECap.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_ECap.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_EPwm.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_EPwm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_EPwm.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_EQep.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_EQep.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_EQep.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_Emif.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_Emif.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_Emif.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_Gpio.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_Gpio.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_Gpio.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_I2C.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_I2C.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_I2C.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_Ipc.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_Ipc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_Ipc.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_Ipc_Driver.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_Ipc_Driver.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_Ipc_Driver.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_Ipc_Driver_Lite.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_Ipc_Driver_Lite.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_Ipc_Driver_Lite.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_Ipc_Driver_Util.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_Ipc_Driver_Util.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_Ipc_Driver_Util.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_Mcbsp.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_Mcbsp.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_Mcbsp.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_PieCtrl.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_PieCtrl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_PieCtrl.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_PieVect.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_PieVect.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_PieVect.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_Sci.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_Sci.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_Sci.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_Spi.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_Spi.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_Spi.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_SysCtrl.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_SysCtrl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_SysCtrl.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_TempSensorConv.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_TempSensorConv.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_TempSensorConv.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_Upp.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_Upp.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_Upp.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_sci_io.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_sci_io.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_sci_io.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_sdfm_drivers.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_sdfm_drivers.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_sdfm_drivers.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_struct.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_struct.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_struct.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

device_support/F2837xD_common/source/F2837xD_usDelay.obj: D:/code/SVN/gs/workspace/device_support/F2837xD_common/source/F2837xD_usDelay.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/bin/cl2000" -v28 -ml -mt --cla_support=cla1 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -O4 --opt_for_speed=5 --fp_mode=relaxed --include_path="D:/code/SVN/gs/workspace/projcet/ginv_cpu1" --include_path="D:/code/SVN/gs/workspace/source/ginv_cpu1/algorithm" --include_path="D:/greenSoftware/CCS7.1.0.00016/ccsv7/tools/compiler/ti-cgt-c2000_16.9.1.LTS/include" --include_path="D:/code/SVN/gs/workspace/public" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_headers/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/include/FlashAPI" --include_path="D:/code/SVN/gs/workspace/device_support/F2837xD_common/driverlib" --advice:performance=all --define=CPU1 --define=_FLASH --define=_STANDALONE -g --c99 --diag_warning=225 --diag_wrap=off --display_error_number --emit_warnings_as_errors --preproc_with_compile --preproc_dependency="device_support/F2837xD_common/source/F2837xD_usDelay.d" --obj_directory="device_support/F2837xD_common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


